export const playlist = [
    "https://jetsetradio.live/radio/stations/lofi/Adam Kay - Rehab (Instrumental).mp3",
    "https://jetsetradio.live/radio/stations/lofi/Aekasora - almost there.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Afternoon - spring (w park bird).mp3",
    "https://jetsetradio.live/radio/stations/lofi/Aftrthght - I Think Of You When I Walk Alone.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Altitude - lake serene.mp3",
    "https://jetsetradio.live/radio/stations/lofi/App - Meaning to Call (5 Centimeters Per Second).mp3",
    "https://jetsetradio.live/radio/stations/lofi/App - My First.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Aqualina - Love Letters W-eiiwun.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Aso - Coffee.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Bassti - To all the ladies in the place.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Bknapp - Game Over (Super Mario Lofi).mp3",
    "https://jetsetradio.live/radio/stations/lofi/blvknight - decembr.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Burbank - A Beautiful Name.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Burbank - Moonlights.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Burbank - The Shadow Of Your Smile.mp3",
    "https://jetsetradio.live/radio/stations/lofi/cat naps - hazy dreams.mp3",
    "https://jetsetradio.live/radio/stations/lofi/chief - dozing off with less people.mp3",
    "https://jetsetradio.live/radio/stations/lofi/city girl - walking in the rain to a cafe.mp3",
    "https://jetsetradio.live/radio/stations/lofi/cormac - summer wind.mp3",
    "https://jetsetradio.live/radio/stations/lofi/DDA - Hip Hop Sample.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Delayde - Sekao.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Desired - 18 Make Up.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Desired - Old Tape.mp3",
    "https://jetsetradio.live/radio/stations/lofi/DJ Cutman - Ballad of the Wind Fish (MeowMeow & BowWow).mp3",
    "https://jetsetradio.live/radio/stations/lofi/DJ Cutman - Meet at the Crossroads (Persona 5 Remix).mp3",
    "https://jetsetradio.live/radio/stations/lofi/DJ Shadow - Why hip hop sucks in 96.mp3",
    "https://jetsetradio.live/radio/stations/lofi/DLJ - The Place (Feat J'san).mp3",
    "https://jetsetradio.live/radio/stations/lofi/DOMINANT - birthday pt 20.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Dontcry - Moon.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Dontcry & Nokiaa - Misunderstood.mp3",
    "https://jetsetradio.live/radio/stations/lofi/driver - the eye of truth.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Dubvalentino - Pleasure.mp3",
    "https://jetsetradio.live/radio/stations/lofi/elijah who - uber to your place.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Eric Godlow Beats - Hopeful.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Falcxne - Beachside Dreaming.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Fallen Roses - Guilty Pleasures (feat. Greco).mp3",
    "https://jetsetradio.live/radio/stations/lofi/flowers - in love with a ghost (feat. nori).mp3",
    "https://jetsetradio.live/radio/stations/lofi/Frad - The Girl I Have A Crush On.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Fujitsu - Motions.mp3",
    "https://jetsetradio.live/radio/stations/lofi/furino - Medusas.mp3",
    "https://jetsetradio.live/radio/stations/lofi/GentleBeatz - Silent Thoughts.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Hakaisu - Shelter (ft Alys).mp3",
    "https://jetsetradio.live/radio/stations/lofi/Halberd - Nvm.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Hm Surf  - Sid's Lesson.mp3",
    "https://jetsetradio.live/radio/stations/lofi/Ibrahim - Bullet Train Fantasy (w luvbird).mp3",
]